[phases.setup]
nixPkgs = ["go"]

[phases.build]
cmds = ["go build -o minio"]

[start]
cmd = "./minio server /data --console-address ':9001'"

[[ports]]
port = 9000
name = "API"

[[ports]]
port = 9001
name = "Console"